version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    parameters:
      node-version:
        type: string
    executor:
      name: node/default
      tag: << parameters.node-version >>
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - run: npm ci
      - run: npm run --workspaces --if-present build
      - run: npm --workspaces test

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          name: gallium
          node-version: '16.18'
      - build-and-test:
          name: hydrogen
          node-version: '18.15'
