version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    parameters:
      node-version:
        type: string
    executor:
      name: node/default
      tag: << parameters.node-version >>
    steps:
      - checkout
      - node/with-cache:
          cache-key: common/config/rush/pnpm-lock.yaml
          dir: ~/project/common/temp
          steps:
            - run:
                name: rush change -v
                command: node common/scripts/install-run-rush.js change -v
            - run:
                name: rush install
                command: node common/scripts/install-run-rush.js install
            - run:
                name: rush rebuild --verbose
                command: node common/scripts/install-run-rush.js rebuild --verbose
            - run:
                name: rush test
                command: node common/scripts/install-run-rush.js test
  deploy:
    executor:
      name: node/default
      tag: "14"
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e2:f9:0e:ba:2c:c0:7e:ca:5d:18:ef:f2:1c:b5:a4:20"
      - run:
          name: Configure git
          command: |-
            git config user.email "rush@scharley.me"
            git config user.name "Rush Releases"
      - run:
          name: rush install
          command: node common/scripts/install-run-rush.js install
      - run:
          name: rush version --bump
          command: node common/scripts/install-run-rush.js version --bump -b master
      - run:
          name: rush publish
          command: node common/scripts/install-run-rush.js publish --publish --include-all -b master --npm-auth-token "$NPM_TOKEN" --set-access-level public

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          name: erbium
          node-version: "12"
      - build-and-test:
          name: fermium
          node-version: "14"
      - deploy:
          context: semantic-release
          requires: [ "erbium", "fermium" ]
          filters:
            branches: { only: master }
