version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: "12.16"
    steps:
      - checkout
      - node/with-cache:
          cache-key: common/config/rush/shrinkwrap.yaml
          dir: ~/project/common/temp
          steps:
            - run:
                name: rush change -v
                command: node common/scripts/install-run-rush.js change -v
            - run:
                name: rush install
                command: node common/scripts/install-run-rush.js install
            - run:
                name: rush rebuild --verbose
                command: node common/scripts/install-run-rush.js rebuild --verbose
            - run:
                name: rush test
                command: node common/scripts/install-run-rush.js test
workflows:
    build-and-test:
      jobs:
        - build-and-test
