module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  plugins: [
    '@typescript-eslint',
  ],
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
  ],
  env: {
    "commonjs": true,
    "es6": true,
    "es2017": true,
  },
  reportUnusedDisableDirectives: true,
  rules: {
    "array-callback-return": "error",
    "arrow-parens": [ "error", "always" ],
    "arrow-spacing": "error",
    "block-scoped-var": "warn",
    "brace-style": [ "error", "stroustrup" ],
    "complexity": [ "warn", { max: 20 } ],
    "comma-dangle": [ "error", "always-multiline" ],
    "consistent-return": "error",
    "curly": "error",
    "default-case": "error",
    "dot-location": [ "error", "property" ],
    "dot-notation": "warn",
    "eol-last": "error",
    "eqeqeq": [ "error", "always", { null: "ignore" } ],
    "generator-star-spacing": [ "error", "after" ],
    "grouped-accessor-pairs": [ "error", "getBeforeSet" ],
    "guard-for-in": "warn",
    "linebreak-style": ["error", "unix"],
    "no-alert": "warn",
    "no-await-in-loop": "error",
    "no-buffer-constructor": "error",
    "no-console": "warn",
    "no-duplicate-imports": "error",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-fallthrough": "error",
    "no-floating-decimal": "error",
    "no-global-assign": "error",
    "no-implicit-coercion": "error",
    "no-implied-eval": "error",
    "no-iterator": "error",
    "no-lone-blocks": "warn",
    "no-lonely-if": "error",
    "no-loop-func": "error" ,
    "no-magic-numbers": [ "warn", { enforceConst: false, ignoreArrayIndexes: true } ],
    "no-multi-spaces": [ "error", { exceptions: { VariableDeclarator: true } } ],
    "no-multi-str": "error",
    "no-new": "error",
    "no-new-func": "error",
    "no-octal": "error",
    "no-octal-escape": "error",
    "no-param-reassign": "error",
    "no-process-exit": "warn",
    "no-proto": "error",
    "no-prototype-builtins": "warn",
    "no-return-assign": ["error", "always"],
    "no-return-await": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-shadow": "error",
    "no-sync": "error",
    "no-template-curly-in-string": "warn",
    "no-throw-literal": "error",
    "no-unexpected-multiline": "error",
    "no-use-before-define": "error",
    "no-useless-call": "error",
    "no-useless-computed-key": "error",
    "no-useless-concat": "warn",
    "no-useless-constructor": "error",
    "no-useless-rename": "error",
    "no-useless-return": "error",
    "no-var": "error",
    "no-void": "error",
    "no-warning-comments": "warn",
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "prefer-numeric-literals": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-regex-literals": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    "require-atomic-updates": "warn",
    "require-await": "error",
    "require-unicode-regexp": "warn",
    "rest-spread-spacing": ["error", "never" ],
    "semi": "error",
    "sort-imports": [ "error", { ignoreCase: true } ],
    "symbol-description": "error",
  },
};
