name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    uses: mscharley/.github/.github/workflows/changesets.yml@607da10e9d82a5578e0a307efdf9983020e43b87 # main
    with:
      node-version-file: .tool-versions
    permissions:
      contents: write
      id-token: write
    secrets:
      token: ${{ secrets.DEPENDENCY_UPDATE_GITHUB_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}
